/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ertu.proje4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ergul
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel(String uuid) {
        initComponents();
        // Store the logged admin account's uuid to be used.
        this.uuid = uuid;
        
        try (Connection conn = DriverManager.getConnection(DBCredentials.db_url, DBCredentials.db_username, 
                DBCredentials.db_password)) {
            // Retrieve all of the user's information
            String query = "SELECT email, password, fullname, birthday FROM members WHERE uuid = ?";
            
            try (PreparedStatement statement = conn.prepareStatement(query)) {
                statement.setString(1, uuid);
                
                ResultSet result_set = statement.executeQuery();
                if (result_set.next()) {
                    String admin_email = result_set.getString("email");
                    String admin_password = result_set.getString("password");
                    String admin_fullname = result_set.getString("fullname");
                    
                    // SQL's DATE type is converted to day/month/year string.
                    java.sql.Date sql_date = result_set.getDate("birthday");
                    LocalDate admin_birthday = sql_date.toLocalDate();
                    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    String birthday_str = admin_birthday.format(dateFormatter);
                    
                    // Info is displayed in the frame
                    nameLabel.setText(admin_fullname);
                    emailLabel.setText(admin_email);
                    
                    // Password is hidden while hinting the length
                    String password_str = "*".repeat(admin_password.length());
                    passwordLabel.setText(password_str);
                    
                    birthdayLabel.setText(birthday_str);
                    
                    uuidLabel.setText(uuid);
                }
                result_set.close();
                statement.close();
                conn.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                            "Database error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        uuidLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        managementMenu = new javax.swing.JMenu();
        booksMI = new javax.swing.JMenuItem();
        adminsMI = new javax.swing.JMenuItem();
        usersMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Welcome!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Name:");

        nameLabel.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Email:");

        emailLabel.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Birthday:");

        birthdayLabel.setText("__/__/____");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Password:");

        passwordLabel.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("UUID:");

        uuidLabel.setText("jLabel10");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uuidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(birthdayLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(uuidLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(logOutButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        managementMenu.setText("Management");

        booksMI.setText("Books");
        booksMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksMIActionPerformed(evt);
            }
        });
        managementMenu.add(booksMI);

        adminsMI.setText("Admins");
        adminsMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminsMIActionPerformed(evt);
            }
        });
        managementMenu.add(adminsMI);

        usersMI.setText("Users");
        usersMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersMIActionPerformed(evt);
            }
        });
        managementMenu.add(usersMI);

        jMenuBar1.add(managementMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // If the user wants to update information, proceed to AccountUpdate dialog
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        AccountUpdate update_panel = new AccountUpdate(this, true, uuid, nameLabel.getText(),
                birthdayLabel.getText(), passwordLabel.getText(), emailLabel.getText());
        update_panel.setLocationRelativeTo(this);
        update_panel.setVisible(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    
    private void adminsMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminsMIActionPerformed
        // Spawn the admin management frame
        AdminManagement admin_manager = new AdminManagement(this, true, uuid);
        admin_manager.setLocationRelativeTo(this);
        admin_manager.setVisible(true);
    }//GEN-LAST:event_adminsMIActionPerformed

    private void usersMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersMIActionPerformed
        // Spawn the user management frame
        UserManagement user_manager = new UserManagement(this, true);
        user_manager.setLocationRelativeTo(this);
        user_manager.setVisible(true);
    }//GEN-LAST:event_usersMIActionPerformed

    private void booksMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksMIActionPerformed
        // Spawn the book management frame
        BookManagement book_manager = new BookManagement(this, true);
        book_manager.setLocationRelativeTo(this);
        book_manager.setVisible(true);
    }//GEN-LAST:event_booksMIActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // In case of an update, the focus returns to admin panel after accountUpdate frame
        // For cases like this, account information is retrieved and redisplayed every time this frame gains focus
        try (Connection conn = DriverManager.getConnection(DBCredentials.db_url, DBCredentials.db_username, 
                DBCredentials.db_password)) {
            String query = "SELECT email, password, fullname, birthday FROM members WHERE uuid = ?";
            
            try (PreparedStatement statement = conn.prepareStatement(query)) {
                statement.setString(1, uuid);
                
                ResultSet result_set = statement.executeQuery();
                if (result_set.next()) {
                    String admin_email = result_set.getString("email");
                    String admin_password = result_set.getString("password");
                    String admin_fullname = result_set.getString("fullname");
                    
                    java.sql.Date sql_date = result_set.getDate("birthday");
                    LocalDate admin_birthday = sql_date.toLocalDate();
                    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    String birthday_str = admin_birthday.format(dateFormatter);
                    
                    nameLabel.setText(admin_fullname);
                    emailLabel.setText(admin_email);
                    
                    String password_str = "*".repeat(admin_password.length());
                    passwordLabel.setText(password_str);
                    
                    birthdayLabel.setText(birthday_str);
                    
                    uuidLabel.setText(uuid);
                }
                result_set.close();
                statement.close();
                conn.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                            "Database error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // Redirects to login frame and disposes of this class
        Login login_frame = new Login();
        login_frame.setLocationRelativeTo(this);
        login_frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private String uuid;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adminsMI;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JMenuItem booksMI;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JMenu managementMenu;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JMenuItem usersMI;
    private javax.swing.JLabel uuidLabel;
    // End of variables declaration//GEN-END:variables
}
